from django.contrib.auth.models import AbstractUser
from django.db import models
from uuid import uuid4
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Custom user model.
    Overrides base Django user model for custom needs.
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid4,
        help_text=_('ID generated by system'),
        editable=False
    )

    def get_token(self) -> str:
        """
        Creates a unique token identifying this user

        Returns:
            str: The token
        """
        return self.id.hex
    
    def __str__(self) -> str:
        return self.username
