from django.db import models
from django.utils.translation import gettext_lazy as _
from uuid import uuid4


class UUIDMixin(models.Model):
    """
    Substitutes django default Id for an UUIDField
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid4,
        help_text=_('ID generated by system'),
        editable=False
    )

    class Meta:
        abstract = True
